skos:
  path: ../resources/be/vlaanderen/omgeving/data/id/conceptscheme/
  name: matrix
  turtle: .ttl
  jsonld: .jsonld
  jsonld_framed: _prefix.jsonld
  csv: .csv
  nt: .nt

source:
  path: ../resources/source/
  codelijst_csv: codelijst-source.csv
  codelijst_context: codelijst_context.json
  codelijst_csv_result_context: codelijst_csv_result_context.json
  catalog_context: catalog_context.json
  pom_context: pom_context.json

dcat:
  path_catalog: ../resources/be/vlaanderen/omgeving/data/id/catalog/
  path_dataset: ../resources/be/vlaanderen/omgeving/data/id/dataset/
  name: codelijst-matrix
  dataset_jsonld: dataset.jsonld
  dataset_turtle: dataset.ttl
  catalog_turtle: catalog.ttl
  catalog_jsonld: catalog.jsonld


sparql :
  verrijking_dcat : ../sparql/verrijk_dcat.rq
  construct : ../sparql/construct.rq
  dataset_source : ../sparql/dataset_source_full_uri.rq

ap :
  path: ../resources/be/vlaanderen/omgeving/data/id/ontology/
  type: ap-constraints
  name: matrix
  turtle: .ttl

n3 :
  skos_rules : ../n3/skos-rules.n3